SHOW DATABASES; /*Listar base de datos*/

CREATE DATABASE dbMinimarket;/*Crea base de datos*/

USE dbMinimarket;

/*Crear la tablas*/
CREATE TABLE VENDEDOR(
    CODVEND CHAR(6),
    NOMVEN VARCHAR(50),
    APEVEN VARCHAR(80),
    DOCVEN VARCHAR(10),
    CELVEN CHAR(9),
    DOMVEN VARCHAR(80),
    PRIMARY KEY (CODVEND)
);

CREATE TABLE CLIENTE(
    CODCLI CHAR(6),
    NOMCLI VARCHAR(40),
    APECLI VARCHAR(80),
    CELCLI CHAR(9),
    EMAILCLI VARCHAR(50),
    FECNACCLI DATE,
    PRIMARY KEY (CODCLI)
);

CREATE TABLE VENTA(
    IDVENT INTEGER,
    FECVENT DATE,
    TIPVENT CHAR(1),
    PRIMARY KEY(IDVENT)
);

CREATE TABLE PRODDUCTO(
    CODPRO CHAR(6),
    NOMPRO VARCHAR(50),
    PREPRO DECIMAL(8,2),
    STOCKPRO INTEGER,
    PRIMARY KEY (CODPRO)
);

CREATE TABLE VENTA_DETALLE(
    IDVENTDET INTEGER,
    CANTVENTDET INTEGER,
    PRIMARY KEY (IDVENTDET)
);